### Create a game
< {%
    client.global.set("gameTitle", crypto.randomUUID())
%}
POST http://localhost:8080/games
Content-Type: application/json

{
  "title": "{{gameTitle}}",
  "startTime": "2026-06-25T12:00:00Z",
  "endTime": "2026-06-25T12:00:00Z",
  "map": {
    "cornerA": {
      "latitude": 53.0,
      "longitude": 54.0
    },
    "cornerB": {
      "latitude": 53.0,
      "longitude": 54.0
    },
    "grid": {
      "rows": 20,
      "columns": 20
    }
  }
}

> {%
    const gameId = response.headers.valueOf("X-GameId")
    client.global.set("gameId", gameId)

    client.test("Game ID is present", () => {
        client.assert(gameId !== null)
    });
%}

### Create an angent
POST http://localhost:8080/games/{{gameId}}/agents
Content-Type: application/json

{
  "firstName": "Tom",
  "lastName": "Lausmann",
  "alias": "Lausi",
  "phoneNumber": "01754242277",
  "active": true,
  "type": "MISTERX"
}

> {%
    const agentId = response.headers.valueOf("X-AgentId")
    client.global.set("agentId", agentId)

    client.test("Agent ID is present", () => {
        client.assert(agentId !== null)
    })
%}

### Send a location for an agent
POST http://localhost:8080/location
Content-Type: application/json
X-GameId: 3c6d3ac9-836f-4662-92ef-49cbf39a52d8
X-AgentId: 9a030b0b-90c9-4543-9af5-20849db53b43

{
  "latitude": 50.0,
  "longitude": 51.0
}


### Create a Team
POST http://localhost:8080/games/{{gameId}}/teams
Content-Type: application/json

{
  "name": "Die Einzigen"
}

> {%
    const teamId = response.headers.valueOf("X-TeamId")
    client.global.set("teamId", teamId)

    client.test("TeamID is present", () => {
        client.assert(teamId !== null);
    });
%}


### Get my team (member id optional)
GET http://localhost:8080/my-team
X-GameId: {{gameId}}
X-TeamId: {{teamId}}
X-MemberId: {{teamMemberId}}
